### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by rubyFeedback** [nadermx/backgroundremover#1]
How does it work?

Would it be possible to add a paragraph to the main README.md?

I am not looking for a detailed 1:1 source code explanation, but just
the main gist of how the correct pixels are determined and whether
the program may also pick the "wrong pixels" (I assume some
backgrounds will be harder). If you have some time in the future,
a paragraph would be nice in this regard - does not have to be
overly long eithers. Thanks for reading!

**Comment by TheJackiMonster** [comment]
I assume it scans the image for a human, segments the image in parts which are connected to the potentially moving human in the foreground and other parts will be the background via exclusion. Otherwise it would probably not work for animated backgrounds.

Another approach would be using an additional image source of the background only to help separating between background and foreground via differences to the background source. But because there is no such additional source given as parameter in the examples, that doesn't work here.

The most consistent way would probably be an additional input from a depth sensor/camera. So there wouldn't be the requirement of a human or specific object to be recognized in the foreground. However then you had bigger hardware limitations for users of the software. ^^'

**Comment by woctezuma** [comment]
Just check the code:

https://github.com/nadermx/backgroundremover/blob/5cfa5bdc5557fb1b56b610a6f380250a114c201c/src/backgroundremover/bg.py#L183-L189

1) a mask is predicted,
2) then cut-out is performed using:

https://github.com/nadermx/backgroundremover/blob/5cfa5bdc5557fb1b56b610a6f380250a114c201c/src/backgroundremover/bg.py#L7

**Comment by nadermx** [comment]
Thank you @woctezuma I will also add, that the video part, has a [whimsical](https://whimsical.com/ffmpeg-virtual-greenscreen-tS2T9uthKdCWhxvBAFUcy) with a (video)[https://www.youtube.com/watch?v=4NjqR2vCV_k] made by https://github.com/ecsplendid whom is the developer who's code I modified to get it working on this.

**Comment by nadermx** [comment]
@woctezuma I'll also put on the todo to be able to import in different models.
