### ISSUE TITLE
 'utf-8' codec can't decode byte 0xb2 in position 7: invalid start byte

### ISSUE THREAD

**Issue by xiaokai0215** [nadermx/backgroundremover#25]
How to solve it

![1](https://user-images.githubusercontent.com/65208666/149655834-04acb63a-971a-4da5-a3eb-309ef5d66722.png)

**Comment by hi-hmz** [comment]
I had the same problem in windows7 because executed the following command in the transparentvideo function in the backgrounremover/utilities.py file:
`cmd = "nice -10 ffmpeg -y -nostats -loglevel 0 -i %s -i %s -filter_complex '[1][0]scale2ref[mask][main];[main][mask]alphamerge=shortest=1 ' -c:v qtrle -shortest %s" % (
             file_path, temp_file, output)`
` process = sp.Popen(cmd, shell=True, stdout=sp.PIPE, stderr=sp.PIPE)`
`stdout, stderr = process.communicate()`
However, the 'nice' command cannot be used in this system, and the following error will be thrown in the Chinese environment:
'nice' is not an internal or external command, nor is it a runnable program
or batch file.

The stderr may be gbk encoding, use utf-8 decoding to cause 'utf-8' codec can't decode byte 0xb2 in position 7: invalid start byte

I removed 'nice -10 ' when judging the OS as windows,
backgroundremover -i "/path/to/image.jpeg" -o "output.png" works fine, but the output file has only audio and no image.

Both -tg and -mk return the expected results.

**Comment by nadermx** [comment]
This should be fixed with the newest version, `pip install --upgrade backgroundremover`

**Comment by 435781067** [comment]
![image](https://github.com/nadermx/backgroundremover/assets/11382436/168854f9-9c20-4adf-b507-8d4465a63fc9)

**Comment by 435781067** [comment]
I have update this version

**Comment by nadermx** [comment]
If you want to push a pr without nice in tbe utils ffmpeg commands, i will
accept
