### ISSUE TITLE
Any way to increase speed ?

### ISSUE THREAD

**Issue by alagiyanirav** [nadermx/backgroundremover#31]
I have 8 GB RAM Ubuntu in EC2. The image background removal command is taking time around 6-10 seconds but My CPU & RAM is utilizing only 1-10 %

Is there any option to increase the speed via utilizing more resources?

I really appreciate the support of this repo.

**Comment by conrad10781** [comment]
I'm guessing the averages for your CPU and RAM is 1-10% ( unless you're dealing with a very small file ) or depending on what "command" your seeing it might be a thread and not the actual command. If you open a second shell or utilize screen and run something like htop while the backgroundremover command is running you should see something like this ( cropped and edited to hide some information ). You can filter in htop so that you only see backgroundremover.

![Screenshot from 2022-10-20 08-09-06](https://user-images.githubusercontent.com/238705/196945360-e10f4e80-0436-4ca1-b58c-68021528323f.png)

Point being, on the CPU side especially, it's going to be using a lot more than 1-10%, and given that it's probably a "regular" EC2 instance and not one of the P* types ( IE https://aws.amazon.com/ec2/instance-types/p3/ ) you will be bound by your CPU, and you'll find you're already fully utilizing it.

**Comment by alagiyanirav** [comment]
Thanks for the reply. 
Yes, You are right. My avg. CPU is 1-10%. 
If I increase the CPU & RAM then Will it optimize the speed?

**Comment by nadermx** [comment]
You can try changing the batch size or worker number from 1-and up https://github.com/nadermx/backgroundremover#advance-usage-for-video

**Comment by alagiyanirav** [comment]
@nadermx : I am using image background removal so is there any option to increase batch size or worker?
Thanks for the reply.
